health:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: health
    username: root
    password: root
#阿里云oss配置
  alioss:
    endpoint:  oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t92ASgnmzDtvggA8sV2
    access-key-secret: NyJXf33aIJolnBohWRGYBl97605cSh
    bucket-name: sky-itcast-zq
# redis配置
  redis:
    host: localhost
    port: 6379
#    password: 123456
    database: 10
#spring:
#  freemarker:
#    template-loader-path: classpath:/templates/
#    suffix: ftl
#freemarker:
#  out:
#    path: D:\work\沉浸式项目实战\bxg-health-parent\bxg-health-mobile\src\main\resources\mobile\pages