health:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: health
    username: root
    password: root
#阿里云oss配置
  alioss:

# redis配置
  redis:
    host: localhost
    port: 6379
#    password: 123456
    database: 10
